apiVersion: batch/v1
kind: Job
metadata:
  name: mssqltools-job
spec:
  template:
    spec:
      containers:
      - name: mssqltools
        image: mcr.microsoft.com/mssql-tools
        command: [ "/bin/bash", "-c", "/opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P SqlServer2019! -d master -i /tmp/script.sql" ]
        volumeMounts:
        - name: sql-script
          mountPath: /tmp/script.sql
          subPath: script.sql
          readOnly: true
        securityContext:
          runAsUser: 0
      restartPolicy: Never
      volumes:
      - name: sql-script
        configMap:
          name: sql-script-configmap
          items:
          - key: script.sql
            path: script.sql


