apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  hostPath:
    path: C:\Apps\FiapTechChallenge\data
