USE [master]
GO
/****** Object:  Database [TechChallenge]    Script Date: 1/28/2024 20:15:30 ******/
CREATE DATABASE [TechChallenge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TechChallenge', FILENAME = N'/var/opt/mssql/data/TechChallenge.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TechChallenge_log', FILENAME = N'/var/opt/mssql/data/TechChallenge_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TechChallenge] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TechChallenge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TechChallenge] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TechChallenge] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TechChallenge] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TechChallenge] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TechChallenge] SET ARITHABORT OFF 
GO
ALTER DATABASE [TechChallenge] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TechChallenge] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TechChallenge] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TechChallenge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TechChallenge] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TechChallenge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TechChallenge] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TechChallenge] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TechChallenge] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TechChallenge] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TechChallenge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TechChallenge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TechChallenge] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TechChallenge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TechChallenge] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TechChallenge] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TechChallenge] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TechChallenge] SET RECOVERY FULL 
GO
ALTER DATABASE [TechChallenge] SET  MULTI_USER 
GO
ALTER DATABASE [TechChallenge] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TechChallenge] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TechChallenge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TechChallenge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TechChallenge] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TechChallenge] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TechChallenge', N'ON'
GO
ALTER DATABASE [TechChallenge] SET QUERY_STORE = OFF
GO

